GET http://localhost:8080/v1/auth
###
POST http://localhost:8080/v1/auth/login
Content-Type: application/json
{
    "username":"yufechan701@gmail.com",
    "password":"bebasaja"
}
###
GET http://localhost:8080/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inl1ZmVjaGFuNzAxQGdtYWlsLmNvbSIsImxldmVsIjoiZ3VydSIsInBlcm1pc3Npb24iOlsicG9rb2tfanVydXNhbiIsInBva29rX3Nla29sYWgiLCJQUERCX3BlbmRhZnRhcmFuIiwiUFBEQl9hZG1pbmlzdHJhc2kiLCJpbnZlbnRhcmlzIl0sImlhdCI6MTYzNTI5NjkzMH0.v33kkBsDKuyLtfrJRSe6uNGP_ehGe8IcRddiIUfn5sk
###
GET http://localhost:8080/v1/administrasi/student
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inl1ZmVjaGFuNzAxQGdtYWlsLmNvbSIsImxldmVsIjoiZ3VydSIsInBlcm1pc3Npb24iOlsicG9rb2tfanVydXNhbiIsInBva29rX3Nla29sYWgiLCJQUERCX3BlbmRhZnRhcmFuIiwiUFBEQl9hZG1pbmlzdHJhc2kiLCJpbnZlbnRhcmlzIl0sImlhdCI6MTYzNTI5NjkzMH0.v33kkBsDKuyLtfrJRSe6uNGP_ehGe8IcRddiIUfn5sk