GET http://localhost:8080/v1/auth

###

POST http://localhost:8080/v1/auth/login
Content-Type: application/json

{
    "username":"yufechan701@gmail.com",
    "password":"bebasaja"
}

###

GET http://localhost:8080/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZ1bG5lcmFibGV2MSIsImlhdCI6MTYzNTI2MjMxMH0.2HsdNdOty_9emnrQkuUANJX6cMsCgGUpirMChr0kFw4