GET http://localhost:8080/v1/auth
###
POST http://localhost:8080/v1/auth/login
Content-Type: application/json

{
    "username":"cucu.ruhiyatna3@gmail.com",
    "password":"kekaishi123",
    "app": "inventaris"
}

# {
#     "username":"dede.munawar@gmail.com",
#     "password":"kekaishi123",
#     "app": "inventaris"
# }
###
GET http://localhost:8080/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Inl1ZmVjaGFuNzAxQGdtYWlsLmNvbSIsImxldmVsIjoiZ3VydSIsInBlcm1pc3Npb24iOlsicG9rb2tfanVydXNhbiIsInBva29rX3Nla29sYWgiLCJQUERCX3BlbmRhZnRhcmFuIiwiUFBEQl9hZG1pbmlzdHJhc2kiLCJpbnZlbnRhcmlzIl0sImlhdCI6MTYzNTQ0MTIxNH0.49WN-acCiGPAPfQvFEDhioRSZIcqB4o8_isPZXFf2oc
###
GET http://localhost:8080/v1/administrasi/payment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50VHlwZSI6ImFkbWluIiwiZW1haWwiOiJjdWN1LnJ1aGl5YXRuYTNAZ21haWwuY29tIiwibGV2ZWwiOiJzdXBlcnVzZXIiLCJwZXJtaXNzaW9uIjpbXSwiaWF0IjoxNjM2NTk5NDUzfQ.rb1-VQJTmBSaTEn-1kEI6rGWQzBeCL7aVImyGH_xL5I
###
GET http://localhost:8080/v1/administrasi/payment/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50VHlwZSI6ImFkbWluIiwiZW1haWwiOiJjdWN1LnJ1aGl5YXRuYTNAZ21haWwuY29tIiwibGV2ZWwiOiJzdXBlcnVzZXIiLCJwZXJtaXNzaW9uIjpbXSwiaWF0IjoxNjM2NTk5NDUzfQ.rb1-VQJTmBSaTEn-1kEI6rGWQzBeCL7aVImyGH_xL5I
###
GET http://localhost:8080/v1/class
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50VHlwZSI6ImFkbWluIiwiZW1haWwiOiJjdWN1LnJ1aGl5YXRuYTNAZ21haWwuY29tIiwibGV2ZWwiOiJzdXBlcnVzZXIiLCJwZXJtaXNzaW9uIjpbXSwiaWF0IjoxNjM3MTU3NDgxfQ.69Os2t6XMyd7x5X5Egf6gcKRPEha5nmNvyILj3cAnz0
###
POST http://localhost:8080/v1/administrasi/payment/1/invoices
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50VHlwZSI6ImFkbWluIiwiZW1haWwiOiJjdWN1LnJ1aGl5YXRuYTNAZ21haWwuY29tIiwibGV2ZWwiOiJzdXBlcnVzZXIiLCJwZXJtaXNzaW9uIjpbXSwiaWF0IjoxNjM2NjAwMTczfQ.4D7OWT2zaC9UxOz_-SRvpM3uRrxrYgHNz9mgjQUztN4
Content-Type: application/json

{
    "class":[2,3,5,6],
    "prodi":[2]
}